version: 2
workflows:
  version: 2
  build-and-deploy-with-manual-approval:
    jobs:
      - build
      - approve-deployment:
          type: approval
      - deploy:
          requires:
            - build
            - approve-deployment
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - run: echo "This is a build step"
      
  deploy:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - run: echo "This is a deploy step"
